# Generated by Django 3.2.10 on 2021-12-09 20:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
