# Generated by Django 3.2.10 on 2021-12-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
    ]
