# Generated by Django 3.2.10 on 2021-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
