# Generated by Django 3.2.10 on 2021-12-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20211213_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='contact_type',
            new_name='email_type',
        ),
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='contact_type',
            new_name='phonenumber_type',
        ),
    ]
