# Generated by Django 3.2.10 on 2021-12-14 00:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20211213_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
