# Generated by Django 3.2.10 on 2021-12-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_phonenumbers_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email_type',
            field=models.CharField(choices=[('pers', 'Personal'), ('work', 'Work')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phonenumber_type',
            field=models.CharField(choices=[('home', 'Home'), ('mob', 'Mobile'), ('work', 'Work')], default='1', max_length=4),
        ),
    ]
