# Generated by Django 3.2.10 on 2022-01-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contacts_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='email',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='emails',
            old_name='email_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='phoneNumber',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='phonenumber_type',
            new_name='type',
        ),
    ]
